### ISSUE TITLE
Task :pushwoosh-react-native-plugin:verifyReleaseResources FAILED

### ISSUE THREAD

**Issue by MrDatastorage** [Pushwoosh/pushwoosh-react-native-plugin#58] opened 2019-04-19 08:43 UTC
### Setup 
-     "react-native": "0.59.5"
-     "pushwoosh-react-native-plugin": "^5.14.0"
### Android Gradle Settings:
- buildToolsVersion = "28.0.3"
- minSdkVersion = 16
- compileSdkVersion = 28
- targetSdkVersion = 28
- supportLibVersion = "28.0.0"
- classpath 'com.android.tools.build:gradle:3.3.1'

### ERROR ON ANDROID BUILD
'''> Task :pushwoosh-react-native-plugin:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pushwoosh-react-native-plugin:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /Users/facebookAD3918/gitlab/test/node_modules/pushwoosh-react-native-plugin/src/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  /Users/facebookAD3918/gitlab/test/node_modules/pushwoosh-react-native-plugin/src/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  /Users/facebookAD3918/gitlab/test/node_modules/pushwoosh-react-native-plugin/src/android/build/intermediates/res/merged/release/values/values.xml:3185: error: resource android:attr/fontVariationSettings not found.
  /Users/facebookAD3918/gitlab/test/node_modules/pushwoosh-react-native-plugin/src/android/build/intermediates/res/merged/release/values/values.xml:3186: error: resource android:attr/ttcIndex not found.
  error: failed linking references.'''

**Comment by wfhm** [comment] 2019-04-19 08:49
Hi @MrDatastorage ,

Looks like a duplicate of [#53](https://github.com/Pushwoosh/pushwoosh-react-native-plugin/issues/53). Please try the solution described in the linked issue and let us know about results.

**Comment by MrDatastorage** [comment] 2019-04-19 11:02
> Hi @MrDatastorage ,
> 
> Looks like a duplicate of [#53](https://github.com/Pushwoosh/pushwoosh-react-native-plugin/issues/53). Please try the solution described in the linked issue and let us know about results.

Hi @wfhm ,

Check my Gradle build settings in this issue ticket.
-  supportLibVersion = "28.0.0".
Still the same error.

**Comment by MrDatastorage** [comment] 2019-04-19 11:14
Didn't read it good.

**Comment by MrDatastorage** [comment] 2019-04-19 12:53
@wfhm 
I have changed in the modules the following:
'''  implementation "com.android.support:appcompat-v7:28.+"
    implementation "com.android.support:recyclerview-v7:28.+"
    api "com.android.support:design:28.+"
'''
It is still not working

**Comment by wfhm** [comment] 2019-04-23 10:31
@MrDatastorage 

You specify `supportLibVersion = "28.0.0"` in your gradle settings, however in the plugin you have 28.+ version. The minor versions should also match - could you please check which version was used in your project, or, better, just set it to 28.0.0 and let us know about results?

**Comment by wfhm** [comment] 2019-05-15 11:30
@MrDatastorage any news on this one?

**Comment by mgpepe** [comment] 2019-06-04 04:05
I have the same issue:
```
Execution failed for task ':pushwoosh-react-native-plugin:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /Users/vagrant/git/node_modules/pushwoosh-react-native-plugin/src/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  /Users/vagrant/git/node_modules/pushwoosh-react-native-plugin/src/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  /Users/vagrant/git/node_modules/pushwoosh-react-native-plugin/src/android/build/intermediates/res/merged/release/values/values.xml:3185: error: resource android:attr/fontVariationSettings not found.
  /Users/vagrant/git/node_modules/pushwoosh-react-native-plugin/src/android/build/intermediates/res/merged/release/values/values.xml:3186: error: resource android:attr/ttcIndex not found.
  error: failed linking references.
```

Gradle:
```// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.1'
        classpath 'com.google.gms:google-services:4.2.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
```

Versions:
```
RN: "0.59.3"
pushwoosh-react-native-plugin: "5.14.2"
```

**Comment by wfhm** [comment] 2019-06-10 06:10
@mgpepe the issue is caused by different versions of Android support libs used in your project by different plugins. You can find instructions on resolving this particular conflict in [this issue](https://github.com/Pushwoosh/pushwoosh-react-native-plugin/issues/53).

**Closed by wfhm** 2019-06-10 06:10 UTC
