### ISSUE TITLE
[Bug]: Push notifications not working on latest version of RN on Android

### ISSUE THREAD

**Issue by AlbinNewSeed** [Pushwoosh/pushwoosh-react-native-plugin#153] opened 2023-11-29 15:04 UTC
### Documentation

- [X] I've checked the guide, but it doesn't help me to resolve the issue.

### Description

version: 6.1.24

App registers push notification correctly without errors according to the library on Android,
and an FCM token is received.
However, when I go to test devices on the website and try to add the token manually to register my test device, it gives me error and says that the token isn't registered to any device.

### Bug severity

High

### Steps to Reproduce

1. Create project with latest RN version "react-native": "0.72.6",
2. Register and init for push notifications with Pushwoosh
3. Copy the FCM Token
4. Attempt to register test device in Pushwoosh website manually using FCM Token
5. Send push notification to Test devices

Let me know if anyone succeeds in receiving a push notification on Android 14
buildToolsVersion = "33.0.1"
minSdkVersion = 24
compileSdkVersion = 33
targetSdkVersion = 33

### Your Pushwoosh React Native Plugin version

Other — specify it in the description

### Affected platforms

- [X] Android
- [ ] iOS

### Affected OS versions and/or devices

Android 14 - Pixel 8 Pro

**Comment by AlbinNewSeed** [comment] 2023-11-29 15:05
Mistake above; bug severity should not be low

**Comment by shahjahanpak** [comment] 2023-11-30 12:18
I am not getting pushing notifications on android either. Sometimes killing the app would trigger 'em but can't say for sure, it is intermittent. 
 
"react-native": "0.72.6"
"pushwoosh-react-native-plugin": "6.1.24"

buildToolsVersion = "33.0.0"
minSdkVersion = 24
compileSdkVersion = 33
targetSdkVersion = 33
kotlinVersion = "1.6.10"
ndkVersion = "23.1.7779620"
playServicesLocationVersion = "21.0.1"

**Comment by shahjahanpak** [comment] 2023-12-01 15:37
As a quick workaround I downgraded pushwoosh-react-native-plugin to 6.1.16. Now I can get push notifications on android.

**Comment by enginseer-dev** [comment] 2023-12-04 09:09
Confirmed, will be fixed with the next release.

**Comment by wfhm** [comment] 2023-12-19 14:04
Sorry for the late reply, the issue was fixed with the 6.1.26 release.

**Closed by wfhm** 2023-12-19 14:04 UTC
Labels: bug

**Comment by AlbinNewSeed** [comment] 2023-12-22 16:51
> Sorry for the late reply, the issue was fixed with the 6.1.26 release.

Still not working for me though. What was fixed? Can't see any fix in the commit history related to Android.

**Comment by enginseer-dev** [comment] 2023-12-22 17:42
Hi @AlbinNewSeed,

In the release notes of the React Native plugin, this information is really missing, but I assume that @wfhm has mentioned changes https://github.com/Pushwoosh/pushwoosh-android-sdk/releases/tag/6.7.0 from the Android SDK which was included to the React Native since 6.1.25.

Do I understand correctly that you updated the plugin to the latest version and built the application from scratch?

Did you clean and build the app using
```
./gradlew clean
./gradlew assembleDebug
```
Or even the following (please be careful)
```
// delete the node_modules folder
rm -rf node_modules
// remove build artifacts
rm -rf android/build
// clear cache
watchman watch-del-all
npm cache clean --force
rm -rf $TMPDIR/react-*
```
?

**Comment by AlbinNewSeed** [comment] 2023-12-22 21:48
> Hi @AlbinNewSeed,
> 
> In the release notes of the React Native plugin, this information is really missing, but I assume that @wfhm has mentioned changes https://github.com/Pushwoosh/pushwoosh-android-sdk/releases/tag/6.7.0 from the Android SDK which was included to the React Native since 6.1.25.
> 
> Do I understand correctly that you updated the plugin to the latest version and built the application from scratch?
> 
> Did you clean and build the app using
> 
> ```
> ./gradlew clean
> ./gradlew assembleDebug
> ```
> 
> Or even the following (please be careful)
> 
> ```
> // delete the node_modules folder
> rm -rf node_modules
> // remove build artifacts
> rm -rf android/build
> // clear cache
> watchman watch-del-all
> npm cache clean --force
> rm -rf $TMPDIR/react-*
> ```
> 
> ?

Will try it, thanks 👍

**Comment by enginseer-dev** [comment] 2023-12-22 21:59
Sure, will be waiting to the results! Just let us know if the issue remains after the upgrade.

**Comment by AlbinNewSeed** [comment] 2023-12-27 10:00
> Sure, will be waiting to the results! Just let us know if the issue remains after the upgrade.

Hi again.

I tried your instructions and it still is not working unfortunately...

Still receiving a token but the token isn't working.

**Comment by enginseer-dev** [comment] 2023-12-27 13:37
@AlbinNewSeed I've integrated the Pushwoosh React Native plugin (6.1.26) in a sample project to replicate your issue. 
In my tests, push notifications were successfully received.

To help troubleshoot your setup, you can refer to this sample project:
https://github.com/enginseer-dev/react_native_basic_sample/tree/main
It might give you insights into any differences in integration.

Remember, React Native requires specific setup for foreground push notifications. You can find the necessary steps here: https://docs.pushwoosh.com/platform-docs/pushwoosh-sdk/cross-platform-frameworks/react-native/integrating-react-native-plugin

For accurate testing, try sending push notifications when the app is in the background or closed.

**Comment by AlbinNewSeed** [comment] 2023-12-27 17:17
> @AlbinNewSeed I've integrated the Pushwoosh React Native plugin (6.1.26) in a sample project to replicate your issue. In my tests, push notifications were successfully received.
> 
> To help troubleshoot your setup, you can refer to this sample project: https://github.com/enginseer-dev/react_native_basic_sample/tree/main It might give you insights into any differences in integration.
> 
> Remember, React Native requires specific setup for foreground push notifications. You can find the necessary steps here: https://docs.pushwoosh.com/platform-docs/pushwoosh-sdk/cross-platform-frameworks/react-native/integrating-react-native-plugin
> 
> For accurate testing, try sending push notifications when the app is in the background or closed.

Ok, I've upgraded the entire project to react 0.73.1 to match the sample project you provided, and upgraded dependencies.
I've double checked every possible line of code is exactly as in your sample project
Still getting the same result; pushwoosh register returns a token which doesn't work. :(

**Comment by enginseer-dev** [comment] 2023-12-28 05:22
@AlbinNewSeed If you add your app code, sender ID and google-services.json to the sample project, does the sample project work in your case?

Also, we need the complete logs from your original app, from installation to expected push notification receipt.

You can send the logs to [help@pushwoosh.com](mailto:help@pushwoosh.com). Don’t forget to reference this specific issue in your email for context.

**Comment by AlbinNewSeed** [comment] 2023-12-28 09:20
> @AlbinNewSeed If you add your app code, sender ID and google-services.json to the sample project, does the sample project work in your case?
> 
> Also, we need the complete logs from your original app, from installation to expected push notification receipt.
> 
> You can send the logs to [help@pushwoosh.com](mailto:help@pushwoosh.com). Don’t forget to reference this specific issue in your email for context.

It's working today in my app without having made any changes since yesterday for some reason. This morning I went and tried a another phone just to be sure my phone isn't bricked for some reason and it worked, and then tried my P8P again and it's working on both. 👍 

I went back to previous branch before the project upgrade (0.72.6-0.73.1) and it's not working there, so something must've done it, I have no clue what though. 

I tried your sample app and it works as well on both phones.

Thanks so much for the help!

**Comment by enginseer-dev** [comment] 2023-12-28 09:37
@AlbinNewSeed I was glad to help!

Have a great New Year!
