### ISSUE TITLE
Android build fails - com.android.tools:common:25.3.3

### ISSUE THREAD

**Issue by travisgreermoguls** [Pushwoosh/pushwoosh-react-native-plugin#44] opened 2018-12-10 17:16 UTC
Android builds are failing as of Friday, December 7th.  From what I can tell, com.android.tools:common:25.3.3 (a dependency of com.android.tools.build:gradle:2.3.3) is no longer present in the jcenter repository.  It also is not in the google repository either (they only have as far back as version 26).

We've been using pushwoosh for a while, running our builds on AppCenter (so a fresh build fetch of all code every time, no caches).  Our builds succeeded Thursday and failed Friday (with no package.json changes).  While we are using an older version (), I've tried upgrading to the latest version ().  It failed, but that makes sense as the latest version still relies on android tools/gradle 2.3.3.

I'm certainly no expert on gradle, so maybe I'm just missing something. Though others appear to be running into the same issue:
https://stackoverflow.com/questions/53677823/cannot-run-existing-android-project-com-android-toolscommon25-3-3/53680522

**Comment by Janealter** [comment] 2018-12-11 12:19
I have the same issue

**Comment by wfhm** [comment] 2018-12-11 12:22
Hi,

Checking it.

**Comment by travisgreermoguls** [comment] 2018-12-11 17:52
Update - It turns out this was a mistake by google / jcenter in trimming too many projects from the jcenter repo.  They are in the process of restoring removed projects.  The main thread is here:
https://issuetracker.google.com/issues/120759347

It turned out that there were several packages we are using that had the same issue, not just pushwoosh.  Pushwoosh just was alphabetically first.  I have no idea how much work it might be, but still could be a good idea to upgrade the android tools gradle package?  

I've updated my answer on SO to include our workaround, in case that's helpful to anyone:
https://stackoverflow.com/questions/53677823/cannot-run-existing-android-project-com-android-toolscommon25-3-3/53680522#53680522

**Comment by Janealter** [comment] 2018-12-13 13:42
The issue is solved, see last messages in https://issuetracker.google.com/issues/120759347

**Comment by wfhm** [comment] 2018-12-17 13:18
@travisgreermoguls @Janealter Thank you so much for your investigation and for following up! Please let me know if you think Pushwoosh should perform any additional actions with this issue - until that, I am closing it.

**Closed by wfhm** 2018-12-17 13:18 UTC
