### ISSUE TITLE
Xcode building errors: [Definition of 'Pushwoosh' must be imported from module 'Pushwoosh.Pushwoosh' before it is required] + [Duplicate interface definition for class 'Pushwoosh']

### ISSUE THREAD

**Issue by mrsasuu** [Pushwoosh/pushwoosh-react-native-plugin#106] opened 2020-07-16 22:49 UTC
# Description
Build fail due to 2 errors right after installing the package as explained [here](https://docs.pushwoosh.com/platform-docs/pushwoosh-sdk/cross-platform-frameworks/react-native/integrating-react-native-plugin).

# Error 1:
`<pathToProject>/<react-native-app>/node_modules/pushwoosh-react-native-plugin/src/ios/PushwooshPlugin/Pushwoosh.h:28:1: Duplicate interface definition for class 'Pushwoosh'`

# Error 2:
`<pathToProject>/<react-native-app>/node_modules/pushwoosh-react-native-plugin/src/ios/PushwooshPlugin/Pushwoosh.m:34:17: Definition of 'Pushwoosh' must be imported from module 'Pushwoosh.Pushwoosh' before it is required`

# Steps To Reproduce
Create a new react-native project => Install pushwoosh-react-native-plugin => install ios pods => open Xcode => build debug on device

# Additional Information
- React Native version: 0.63.1 & 0.61.2
- Platform: iOS
- Operating System: macOS 10.15.5 (19F101)
- Xcode: 11.6 (11E708)

**Comment by zigoval** [comment] 2020-07-20 11:43
I ran into the same issues. I tried deleting build / derived data / pod / nodes_modules but nothings worked.

**Comment by zigoval** [comment] 2020-07-20 12:12
I ran into the same issues, even if it used to works before.
I tried deleting build / derived data / pod / nodes_modules but nothings worked.

I find a way to make it works : 
Error 1:
![Capture d’écran 2020-07-20 à 13 47 31](https://user-images.githubusercontent.com/35451438/87935753-f7855300-ca91-11ea-80dc-adbdd0b3d115.png)
Uncheck pushwoosh-react-native-plugin (Red Arrow) then click on the second error (first blue arrow), red arrow again.
Do it again with the second arrow.
run again.

The error should appear again so you need to do it again.
(2 or 3 times in total i think)

Then it should works. (it did for me).
The first time, i had the error n°2, i changed the import to <Pushwoosh.h>
And i had no error at all.
But if you run pod install again, you need to redo all the step.
(weird thing here, i didn't run into error n°2 the second time, and i have an error on duplicate interface but i can build anyway and my app is working great.

I found several interface Pushwoosh on the node_modules, because there is a public and a private folder. I don't know what does it do. I might come from here.

I hope i was clear enough. Good luck

**Comment by zigoval** [comment] 2020-07-20 12:35
I ran into the same issues, even if it used to works before.
I tried deleting build / derived data / pod / nodes_modules but nothings worked.

I find a way to make it works : 
Error 1:
![Capture d’écran 2020-07-20 à 13 47 31](https://user-images.githubusercontent.com/35451438/87935753-f7855300-ca91-11ea-80dc-adbdd0b3d115.png)
Uncheck pushwoosh-react-native-plugin (Red Arrow) then click on the second error (first blue arrow), red arrow again.
Do it again with the second arrow.
run again.

The error should appear again so you need to do it again.
(2 or 3 times in total i think)

Then it should works. (it did for me).
The first time, i had the error n°2, i changed the import to <Pushwoosh.h>
And i had no error at all.
But if you run pod install again, you need to redo all the step.
(weird thing here, i didn't run into error n°2 the second time, and i have an error on duplicate interface but i can build anyway and my app is working great.

I found several interface Pushwoosh on the node_modules, because there is a public and a private folder. I don't know what does it do. I might come from here.

I hope i was clear enough. Good luck

Edit : it seems that Pushwoosh is not undefined when using react-native run-ios but works fine when using Xcode

**Comment by piotr-marat** [comment] 2020-07-20 20:40
same issue here

**Comment by wfhm** [comment] 2020-07-20 21:04
@mrsasuu, @zigoval, @piotr-marat

Checking it.

**Comment by makarkotlov** [comment] 2020-07-21 10:43
same, after trying @zigoval suggestion build was successful but pushwoosh has become undefined

**Comment by wfhm** [comment] 2020-07-24 13:54
@mrsasuu, @zigoval, @piotr-marat, @makarkotlov,

Got it reproduced, will be fixed with the next release.

Meanwhile, you can use the following workaround - open your iOS project in Xcode, Edit -> refactor -> rename class ".../node_modules/pushwoosh-react-native-plugin/src/ios/PushwooshPlugin/Pushwoosh.h" to PushwooshPlugin.

**Comment by SagivOnoApps** [comment] 2020-07-27 08:20
@wfhm
 
this workaround did half the job for me(perhaps i was doing it wrong)
I managed to compile but still Pushwoosh was null in my app

after some digging the trick that fixed that was
inserting Pushwoosh into RCT_EXPORT_MODULE:
> RCT_EXPORT_MODULE(Pushwoosh);
in `node_modules/pushwoosh-react-native-plugin/src/ios/PushwooshPlugin/Pushwoosh.m`

**Comment by zigoval** [comment] 2020-07-27 14:42
The new update fixed it !! thanks a lot !

**Comment by wfhm** [comment] 2020-07-27 14:44
Fixed with the latest release.

**Closed by wfhm** 2020-07-27 14:44 UTC
Labels: 52320
