### ISSUE TITLE
[Bug]:  ERROR  TypeError: Cannot read property 'init' of null, js engine: hermes

### ISSUE THREAD

**Issue by AlbinNewSeed** [Pushwoosh/pushwoosh-react-native-plugin#152] opened 2023-11-02 17:02 UTC
### Documentation

- [X] I've checked the guide, but it doesn't help me to resolve the issue.

### Description

Cannot call init or register in a fresh react-native project with latest version.

Running into the following error on app launch:

` ERROR  TypeError: Cannot read property 'init' of null, js engine: hermes`

### Bug severity

Low

### Steps to Reproduce

1. Initialize a new react-native project @ 0.72.6
2. Try and run Pushwoosh.init and Pushwoosh.register

### Your Pushwoosh React Native Plugin version

6.1.23

### Affected platforms

- [X] Android
- [ ] iOS

### Affected OS versions and/or devices

Android 14 on a Google Pixel 8 Pro,
"react-native": "0.72.6",

**Comment by enginseer-dev** [comment] 2023-11-03 11:59
Hello, @AlbinNewSeed 

Thank you for bringing this to our attention and for the detailed report. 
We have successfully replicated the issue on our end and are actively investigating the cause. 
We will update you as soon as we find the root cause of the issue.

**Comment by mssoliveira** [comment] 2023-11-03 12:00
Hi, I have the same problem, I built the same code a few days ago and worked normally, but since Tuesday (10/31) I have had this problem.


` ERROR  TypeError: null is not an object (evaluating 'PushwooshModule.init') `

"pushwoosh-react-native-plugin": "^6.1.23",
"react-native": "0.69.6",

**Comment by AlbinNewSeed** [comment] 2023-11-03 12:47
> Hello, @AlbinNewSeed
> 
> Thank you for bringing this to our attention and for the detailed report. We have successfully replicated the issue on our end and are actively investigating the cause. We will update you as soon as we find the root cause of the issue.

Thanks!

**Comment by shahjahanpak** [comment] 2023-11-03 13:45
I am getting the same error 
`TypeError: Cannot read property 'init' of undefined at PushNotification.init`

"pushwoosh-react-native-plugin": "6.1.23",
"react-native": "0.72.4"

**Comment by mssoliveira** [comment] 2023-11-06 11:00
some solution?

**Comment by wfhm** [comment] 2023-11-07 05:39
Fixed in 6.1.24.

**Closed by wfhm** 2023-11-07 05:39 UTC
Labels: bug
