### ISSUE TITLE
Firebase dynamic link always opens in browser first

### ISSUE THREAD

**Issue by SimonErich** [Pushwoosh/pushwoosh-react-native-plugin#90] opened 2020-01-15 10:37 UTC
We have implemented pushwoosh using this plugin, but right now we have the problem, that the dynamic link, we send, always opens in a browser instead of opening the app directly.
If I open the same link from slack or other apps, it works perferctly find and opens the app directly.

As soon as I send it via Pushwoosh, it always opens the app (no matter, how I change the behavior in firebase for the dynamic link).

This is an example link:
https://nkh42.app.goo.gl/Z3AS

Maybe it's just a pushwoosh configuration, that I did wrong, but on android it works perfectly fine.

Do you have any idea, where I can start to check?

**Comment by wfhm** [comment] 2020-01-15 11:41
Duplicate of #78

**Closed by wfhm** 2020-01-15 11:41 UTC
Labels: 46736
